version: "2"
linters:
  enable:
    - cyclop
    - errname
    - errorlint
    - exhaustive
    - gocritic
    - revive
    - staticcheck
  settings:
    cyclop:
      max-complexity: 15
    gocritic:
      enabled-checks:
        - hugeParam
        - rangeExprCopy
        - rangeValCopy
        - indexAlloc
        - deprecatedComment
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
